export const GET_BOOTCAMPAPPLYPROGRESS_REQUEST = 'GET_BOOTCAMPAPPLYPROGRESS_REQUEST' 
export const GET_BOOTCAMPAPPLYPROGRESS_SUCCESS = 'GET_BOOTCAMPAPPLYPROGRESS_SUCCESS' 
export const GET_BOOTCAMPAPPLYPROGRESS_FAILED = 'GET_BOOTCAMPAPPLYPROGRESS_FAILED'

export const DEL_BOOTCAMPAPPLYPROGRESS_REQUEST = 'DEL_BOOTCAMPAPPLYPROGRESS_REQUEST'
export const DEL_BOOTCAMPAPPLYPROGRESS_SUCCESS = 'DEL_BOOTCAMPAPPLYPROGRESS_SUCCESS'
export const DEL_BOOTCAMPAPPLYPROGRESS_FAILED  = 'DEL_BOOTCAMPAPPLYPROGRESS_FAILED'

export const ADD_BOOTCAMPAPPLYPROGRESS_REQUEST = 'ADD_BOOTCAMPAPPLYPROGRESS_REQUEST'
export const ADD_BOOTCAMPAPPLYPROGRESS_SUCCESS = 'ADD_BOOTCAMPAPPLYPROGRESS_SUCCESS'
export const ADD_BOOTCAMPAPPLYPROGRESS_FAILED  = 'ADD_BOOTCAMPAPPLYPROGRESS_FAILED'

