export const GET_BOOTCAMPAPPLY_REQUEST = 'GET_BOOTCAMPAPPLY_REQUEST' 
export const GET_BOOTCAMPAPPLY_SUCCESS = 'GET_BOOTCAMPAPPLY_SUCCESS' 
export const GET_BOOTCAMPAPPLY_FAILED = 'GET_BOOTCAMPAPPLY_FAILED'

export const DEL_BOOTCAMPAPPLY_REQUEST = 'DEL_BOOTCAMPAPPLY_REQUEST'
export const DEL_BOOTCAMPAPPLY_SUCCESS = 'DEL_BOOTCAMPAPPLY_SUCCESS'
export const DEL_BOOTCAMPAPPLY_FAILED  = 'DEL_BOOTCAMPAPPLY_FAILED'

export const ADD_BOOTCAMPAPPLY_REQUEST = 'ADD_BOOTCAMPAPPLY_REQUEST'
export const ADD_BOOTCAMPAPPLY_SUCCESS = 'ADD_BOOTCAMPAPPLY_SUCCESS'
export const ADD_BOOTCAMPAPPLY_FAILED  = 'ADD_BOOTCAMPAPPLY_FAILED'

