export const GET_PROGRAMREVIEW_REQUEST = 'GET_PROGRAMREVIEW_REQUEST' 
export const GET_PROGRAMREVIEW_SUCCESS = 'GET_PROGRAMREVIEW_SUCCESS' 
export const GET_PROGRAMREVIEW_FAILED = 'GET_PROGRAMREVIEW_FAILED'

export const DEL_PROGRAMREVIEW_REQUEST = 'DEL_PROGRAMREVIEW_REQUEST'
export const DEL_PROGRAMREVIEW_SUCCESS = 'DEL_PROGRAMREVIEW_SUCCESS'
export const DEL_PROGRAMREVIEW_FAILED  = 'DEL_PROGRAMREVIEW_FAILED'

export const ADD_PROGRAMREVIEW_REQUEST = 'ADD_PROGRAMREVIEW_REQUEST'
export const ADD_PROGRAMREVIEW_SUCCESS = 'ADD_PROGRAMREVIEW_SUCCESS'
export const ADD_PROGRAMREVIEW_FAILED  = 'ADD_PROGRAMREVIEW_FAILED'

