export const GET_BATCH_REQUEST = 'GET_BATCH_REQUEST' 
export const GET_BATCH_SUCCESS = 'GET_BATCH_SUCCESS' 
export const GET_BATCH_FAILED = 'GET_BATCH_FAILED'

export const DEL_BATCH_REQUEST = 'DEL_BATCH_REQUEST'
export const DEL_BATCH_SUCCESS = 'DEL_BATCH_SUCCESS'
export const DEL_BATCH_FAILED  = 'DEL_BATCH_FAILED'

export const ADD_BATCH_REQUEST = 'ADD_BATCH_REQUEST'
export const ADD_BATCH_SUCCESS = 'ADD_BATCH_SUCCESS'
export const ADD_BATCH_FAILED  = 'ADD_BATCH_FAILED'

