export const GET_BATCHSTUDENT_REQUEST = 'GET_BATCHSTUDENT_REQUEST' 
export const GET_BATCHSTUDENT_SUCCESS = 'GET_BATCHSTUDENT_SUCCESS' 
export const GET_BATCHSTUDENT_FAILED = 'GET_BATCHSTUDENT_FAILED'

export const DEL_BATCHSTUDENT_REQUEST = 'DEL_BATCHSTUDENT_REQUEST'
export const DEL_BATCHSTUDENT_SUCCESS = 'DEL_BATCHSTUDENT_SUCCESS'
export const DEL_BATCHSTUDENT_FAILED  = 'DEL_BATCHSTUDENT_FAILED'

export const ADD_BATCHSTUDENT_REQUEST = 'ADD_BATCHSTUDENT_REQUEST'
export const ADD_BATCHSTUDENT_SUCCESS = 'ADD_BATCHSTUDENT_SUCCESS'
export const ADD_BATCHSTUDENT_FAILED  = 'ADD_BATCHSTUDENT_FAILED'

